feat: add Integration model
surface-security/surface pull request #109
Opened 2023-04-10 14:48 UTC by bogdanoniga

Integration model is meant to be a base model for service integrations (e.g. AWS, GCP, etc.). It serves two main functions:
- Manage the service integrations and related credentials within the UI;
- Manage the actions/commands to be performed per service integration;
- Map assets to service integrations in a similar way as Source model does.

Each service integration has its own particularities and actions, therefore, this model will be inherited and extended per service integration's needs.

2023-04-10 14:56 UTC, DDuarte commented
I like the idea but not the implementation, in particular the hardcoded values in `IntegrationType` - it doesn't allow for composability.

IMO it would be better if each "integration" app registered itself on init, similar to how the django apps already work. It could even be an extended version of [AppConfig](https://docs.djangoproject.com/en/dev/ref/applications/#application-configuration) with metadata relevant for integrations.

2023-04-10 15:17 UTC, bogdanoniga commented
> I like the idea but not the implementation, in particular the hardcoded values in `IntegrationType` - it doesn't allow for composability.
> 
> IMO it would be better if each "integration" app registered itself on init, similar to how the django apps already work. It could even be an extended version of [AppConfig](https://docs.djangoproject.com/en/dev/ref/applications/#application-configuration) with metadata relevant for integrations.

IntegrationType is not an important field, we can rely on the child name

2023-04-10 15:37 UTC, bogdanoniga commented
I was thinking to have an extended Integration model part of new applications (if required) and match the application particularities with an extended list of fields. For instance, a new module named `django-github`, meant to sync data from Github, will extend the Integration model to match Github particularities and actions. Therefore, the credentials will be different for Github compared to other services (e.g. AWS) which requires new fields to be added

2023-04-10 16:17 UTC, bogdanoniga commented
> I like the idea but not the implementation, in particular the hardcoded values in `IntegrationType` - it doesn't allow for composability.
> 
> IMO it would be better if each "integration" app registered itself on init, similar to how the django apps already work. It could even be an extended version of [AppConfig](https://docs.djangoproject.com/en/dev/ref/applications/#application-configuration) with metadata relevant for integrations.

With this proposal I would like to dynamically manage the integrations at application level at any time after deployment not as an integration config at init phase. I'm trying to move away from the current approach which defines integration credentials as env vars to a more dynamic way of creating and managing integrations via UI

2023-04-16 14:00 UTC, bogdanoniga commented
As an example, https://github.com/surface-security/django-github uses Integration model as part of the `testapp`

2023-05-04 11:15 UTC, bogdanoniga commented
somebody has a bit of free time to review this PR?

2023-05-04 13:53 UTC, fopina commented on surface/inventory/models.py
> +from fernet_fields import EncryptedTextField
how is fernet_fields encrypting the field content? Using settings SECRET_KEY?

asking as it could be easier to just implement such field in Surface instead of using a 3rd party package (with more features that we do not use) that might add compatibility/upgrading issues in the future

Does it handle the admin part in any special way? (as in not displaying the secret fields but allowing updating them)

2023-05-04 15:22 UTC, gsilvapt commented on surface/inventory/models.py
> +    name = models.CharField(max_length=255, null=False, blank=False)
```suggestion
    name = models.CharField(max_length=255)
```
Defaults are `=False`

2023-05-04 15:24 UTC, gsilvapt requested changes

2023-05-04 15:24 UTC, gsilvapt commented on surface/inventory/models.py
> +    actions = models.JSONField(null=False, blank=False)
```suggestion
    actions = models.JSONField()
```
Defaults are `=False`.

2023-05-04 15:24 UTC, gsilvapt commented on surface/inventory/models.py
> +    secrets = EncryptedTextField(null=True, blank=False)
```suggestion
    secrets = EncryptedTextField(null=True)
```
Default is `=False`.

2023-05-08 18:40 UTC, bogdanoniga commented on surface/inventory/models.py
> +from fernet_fields import EncryptedTextField
there are 2 ways:
- define FERNET_KEYS for fields encryption;
- use SECRET_KEY by default if FERNET_KEYS are not defined.

In regards to admin part, it handles secrets display and update. Also, it handles some sort of a key rotation if FERNET_KEYS[<new_key>, <old_key>] are defined.  The key rotation is pretty limited meaning that it can only display/update the secrets with both new/old keys, without performing  any secrets "migration". The FERNET_KEYS include a `new key` used to encrypt/decrypt the new secrets, and an `old key` required to handle the "old" secrets. However, when updating the "old" secrets, the `new key` is then used.

Developing the field itself in Surface involves some extra effort which might be covered in its own PR. For this PR I'm considering django-fernet-fields

2025-03-19 11:10 UTC, tcppb commented
Very long discussions... Better to move fast, break fast, recover fast, and re-route as needed.

Closing this based on the fact that it is not maintained anyway due to the different roles of some of the involved parties.

2025-03-19 11:10 UTC, closed without merging